# @todo port releases to v2 https://docs.travis-ci.com/user/deployment-v2/providers/releases/

os: linux
dist: focal

language: go

go:
  - 1.15.6

before_script:
  - sudo apt-get install varnish -y
  - varnishstat -V

script:
  - go build -v
  - sudo $GOROOT/bin/go test -v ./...

after_success:
  - if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./build.sh $TRAVIS_TAG; fi

deploy:
  provider: releases
  api_key:
    secure: eDySTfAst2/hz39o1Lt2OnbNtep/eyeFPIT9WdpK8ajVuXAdP2MAwwotmH30iGjCijLW0k7vzZI7yczHqUSEB0E9qHXhF2LDLeirlSMHVWPl4sRDq1+gn0nHBkgH5jO5vAE3pj+zd/N+4rKutCtOBhsfdZKxDuxJXR8On0wwnCVFVQoIsC7gqM2TGmtFpfSFwVefNHdYyWgh0YMg9JtzUp2mSQr8e0+L4fO5jafhpbFXlTzhxqoPwyI2UhnXRLTjCQWWCjxN+37ij13Y6H9NxEaHJr+t9ejpNbKFfUZmhF/9n2seesoeYC9HEkEWTTjuERc1CQlgtxG+sMk1b0ejZio0QUQbVB1U+aTtac2m3U5k4oEAUhYs4rHKy+QmVSRp3Qmo+PV7CuSv9CKivxhvbMUPpos1eF6CuHR3ZKjn/11VimnhpXJcyl44oM4UfoLsZuOcieWta9fLBd0EO+SIvmaBLljAKRMjrnCpkT9E0dKWgUqyDQzqv5l2WZ7lFT+bWuDJ7WeIwnG59jVOjSwvniFWQwQyJ0BmjjGB4g3ZYSQb8oBj+6RzxoBPpoEewBsypXZoDB0yL7GEqxnHmoVLe7D6R/lG+TeTVMOZLkAw13UNAw1v1VHwe0kjM5zqEMekZaLbmvHVC5hUEUob4xsiQu/qHGelT9+Gq9ICwB8GbWg=
  file:
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.linux-amd64.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.linux-386.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.freebsd-amd64.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.freebsd-386.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.openbsd-amd64.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.openbsd-386.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.netbsd-amd64.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.netbsd-386.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.darwin-amd64.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.darwin-386.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.windows-amd64.tar.gz"
    - "bin/release/prometheus_varnish_exporter-$TRAVIS_TAG.windows-386.tar.gz"
    - "bin/release/dashboards-$TRAVIS_TAG.tar.gz"
    - "bin/release/sha256sums.txt"
  skip_cleanup: true
  on:
    repo: jonnenauha/prometheus_varnish_exporter
    tags: true
